///|
const CANVAS_WIDTH : Double = 480.0

///|
const CANVAS_HEIGHT : Double = 600.0

///|
const GRAVITY : Double = 0.3

///|
const FRICTION : Double = 0.1

///|
/// Background Music Volume
const BACKGROUND_MUSIC_VOLUME : Double = 0.2

///|
/// The force applied to cats when moving
const CAT_MOVE_FORCE : Double = 4.0

///|
/// Pointer Horizontal Acceleration
const PTR_ACC_H : Double = 2.5

///|
/// Pointer Maximum Horizontal Speed
const PTR_MAX_VEC_H : Double = 7.5
